import http from 'node:http';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const port=9352;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const UDD=process.cwd()+'/.tmp/chrome-profile';
fs.mkdirSync(UDD,{recursive:true});
const p=spawn(CHROME,['--headless=new',`--remote-debugging-port=${port}`,`--user-data-dir=${UDD}`,'--no-first-run','--hide-scrollbars','--window-size=1440,1000','about:blank'],{stdio:'ignore',env:{...process.env,TMPDIR:process.cwd()+'/.tmp'}});
await wait(2000);
const get=u=>new Promise((res,rej)=>http.get(u,r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>res(JSON.parse(d)));}).on('error',rej));
const tabs=await get(`http://127.0.0.1:${port}/json`);
const WebSocket=(await import('ws')).default;
const sock=new WebSocket(tabs[0].webSocketDebuggerUrl);
let id=0;const cbs={};
const send=(m,params={})=>new Promise(r=>{const i=++id;cbs[i]=r;sock.send(JSON.stringify({id:i,method:m,params}));});
sock.on('message',d=>{const m=JSON.parse(d);if(m.id&&cbs[m.id])cbs[m.id](m);});
await new Promise(r=>sock.on('open',r));
await send('Page.enable');
fs.mkdirSync('_shots',{recursive:true});
async function snap(path,clip){const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{...clip,scale:1}});fs.writeFileSync(path,Buffer.from(shot.result.data,'base64'));console.log('saved',path,fs.statSync(path).size);}
await send('Page.navigate',{url:'http://localhost:4500/p/reyes-roofing-llc'});
await wait(5000);
await snap('_shots/reyes_hero.png',{x:0,y:0,width:1440,height:1000});
await snap('_shots/reyes_services.png',{x:0,y:1000,width:1440,height:1400});
await send('Page.navigate',{url:'http://localhost:4500/p/reyes-roofing-llc/services'});
await wait(4500);
await snap('_shots/reyes_services_page.png',{x:0,y:0,width:1440,height:2200});
sock.close();p.kill();process.exit(0);
