import http from 'node:http';
import { spawn } from 'node:child_process';
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const port=9347;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const p=spawn(CHROME,['--headless=new',`--remote-debugging-port=${port}`,'--user-data-dir=./.tmp/cprofC78440','--disk-cache-dir=./.tmp/chrome-cache','--hide-scrollbars','--window-size=1440,1000','about:blank'],{stdio:'ignore'});
await wait(2000);
const get=u=>new Promise((res,rej)=>http.get(u,r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>res(JSON.parse(d)));}).on('error',rej));
const tabs=await get(`http://127.0.0.1:${port}/json`);
const WebSocket=(await import('ws')).default;
const pg=tabs.find(t=>t.type==='page')||tabs[0];const sock=new WebSocket(pg.webSocketDebuggerUrl);
let id=0;const cbs={};
const send=(m,params={})=>new Promise(r=>{const i=++id;cbs[i]=r;sock.send(JSON.stringify({id:i,method:m,params}));});
sock.on('message',d=>{const m=JSON.parse(d);if(m.id&&cbs[m.id])cbs[m.id](m);});
await new Promise(r=>sock.on('open',r));
await send('Page.enable');
await send('Runtime.enable');
await send('Page.navigate',{url:'http://127.0.0.1:4500/p/tip-top-roofing-service'});
await wait(4500);
const fs=await import('node:fs');
// Full page height
const ev=await send('Runtime.evaluate',{expression:`JSON.stringify({h:document.body.scrollHeight})`,returnByValue:true});
const {h}=JSON.parse(ev.result.result.value);
fs.writeFileSync('./.tmp/tiptop_h.txt',String(h));
const grab=async(y,ht,name)=>{const s=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y,width:1440,height:ht,scale:1}});fs.writeFileSync(name,Buffer.from(s.result.data,'base64'));};
await grab(0,1000,'./.tmp/tiptop_hero.png');
await grab(950,1450,'./.tmp/tiptop_page.png');
await grab(Math.max(0,h-1550),1450,'./.tmp/tiptop_cta.png');
p.kill();
process.exit(0);
