import http from 'node:http';
import { spawn } from 'node:child_process';
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const port=9392;
const log=(...a)=>console.error('[shot]',...a);
const wait=ms=>new Promise(r=>setTimeout(r,ms));
log('launching chrome');
const p=spawn(CHROME,['--headless=new',`--remote-debugging-port=${port}`,'--hide-scrollbars','--window-size=1440,1000','about:blank'],{stdio:'ignore'});
await wait(2500);
const get=u=>new Promise((res,rej)=>http.get(u,r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>res(JSON.parse(d)));}).on('error',rej));
const tabs=await get(`http://127.0.0.1:${port}/json`);
const target=tabs.find(t=>t.type==='page')||tabs[0];
const WebSocket=(await import('ws')).default;
const sock=new WebSocket(target.webSocketDebuggerUrl);
let id=0;const cbs={};
const send=(m,params={})=>new Promise(r=>{const i=++id;cbs[i]=r;sock.send(JSON.stringify({id:i,method:m,params}));});
sock.on('message',d=>{const m=JSON.parse(d);if(m.id&&cbs[m.id]){const cb=cbs[m.id];delete cbs[m.id];cb(m);}});
await new Promise(r=>sock.on('open',r));
await send('Page.enable');await send('Runtime.enable');
log('navigating');
await send('Page.navigate',{url:'http://localhost:4500/p/blooming-landscape-architecture-pools'});
await wait(4500);
const fs=await import('node:fs');
let shot=await send('Page.captureScreenshot',{format:'png',clip:{x:0,y:0,width:1440,height:900,scale:1}});
fs.writeFileSync('/tmp/blooming_hero.png',Buffer.from(shot.result.data,'base64'));
log('hero written');
// Read the desktop nav link labels to confirm Services is gone
const ev=await send('Runtime.evaluate',{expression:`JSON.stringify([...document.querySelectorAll('header nav .hidden.lg\\\\:flex a, header nav .lg\\\\:flex a')].map(a=>a.textContent.trim()).filter(Boolean))`,returnByValue:true});
log('nav links:',ev.result.result.value);
p.kill();process.exit(0);
