import http from 'node:http';
import fs from 'node:fs';
import { spawn } from 'node:child_process';
const log=m=>fs.appendFileSync('.tmp/shot3.log',m+'\n');
try {
  const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
  const port=9377;
  const wait=ms=>new Promise(r=>setTimeout(r,ms));
  log('spawning chrome');
  const p=spawn(CHROME,['--headless=new',`--remote-debugging-port=${port}`,'--hide-scrollbars','--window-size=1440,1000','about:blank'],{stdio:'ignore'});
  await wait(2500);
  log('fetching tabs');
  const get=u=>new Promise((res,rej)=>http.get(u,r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>res(JSON.parse(d)));}).on('error',rej));
  const tabs=await get(`http://127.0.0.1:${port}/json`);
  log('tabs '+tabs.length);
  const WebSocket=(await import('ws')).default;
  const sock=new WebSocket(tabs[0].webSocketDebuggerUrl);
  let id=0;const cbs={};
  const send=(m,params={})=>new Promise(r=>{const i=++id;cbs[i]=r;sock.send(JSON.stringify({id:i,method:m,params}));});
  sock.on('message',d=>{const m=JSON.parse(d);if(m.id&&cbs[m.id])cbs[m.id](m);});
  await new Promise((r,j)=>{sock.on('open',r);sock.on('error',j);});
  log('socket open');
  await send('Page.enable');
  await send('Page.navigate',{url:'http://localhost:4500/p/tempe-roofing'});
  await wait(4000);
  log('capturing');
  const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y:0,width:1440,height:1000,scale:2}});
  fs.writeFileSync('_shots/tempe_hero.png',Buffer.from(shot.result.data,'base64'));
  log('written');
  p.kill();
  process.exit(0);
} catch(e){ log('ERR '+e.stack); process.exit(2); }
