import http from 'node:http';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const port=9356;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const p=spawn(CHROME,['--headless=new',`--remote-debugging-port=${port}`,'--hide-scrollbars','--window-size=1440,1000','--user-data-dir=./.tmp/chrome-irish','about:blank'],{stdio:'ignore'});
await wait(7000);
const get=u=>new Promise((res,rej)=>http.get(u,r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>res(JSON.parse(d)));}).on('error',rej));
const tabs=await get(`http://127.0.0.1:${port}/json`);
const pageTab=tabs.find(t=>t.type==='page')||tabs[0];
const WebSocket=(await import('ws')).default;
const sock=new WebSocket(pageTab.webSocketDebuggerUrl);
let id=0;const cbs={};
const send=(m,params={})=>new Promise(r=>{const i=++id;cbs[i]=r;sock.send(JSON.stringify({id:i,method:m,params}));});
sock.on('message',d=>{const m=JSON.parse(d);if(m.id&&cbs[m.id])cbs[m.id](m);});
await new Promise(r=>sock.on('open',r));
await send('Page.enable');
await send('Page.navigate',{url:'http://localhost:4500/p/irish-roofing-company'});
await wait(4500);
const {result}=await send('Page.captureScreenshot',{format:'png'});
fs.writeFileSync('./_shots/irish.png',Buffer.from(result.data,'base64'));
p.kill();console.log('ok');process.exit(0);
