import http from 'node:http';
import fs from 'node:fs';
import { spawn } from 'node:child_process';
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const port=9347;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const p=spawn(CHROME,['--headless=new',`--remote-debugging-port=${port}`,`--user-data-dir=/tmp/hawkeye-cdp-${port}`,'--no-first-run','--remote-allow-origins=*','--hide-scrollbars','--window-size=1440,1000','about:blank'],{stdio:'ignore'});
await wait(3500);
const get=u=>new Promise((res,rej)=>http.get(u,r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>res(JSON.parse(d)));}).on('error',rej));
const tabs=await get(`http://127.0.0.1:${port}/json`);
const WebSocket=(await import('ws')).default;
setTimeout(()=>{console.log('TIMEOUT');process.exit(2);},20000).unref();
const sock=new WebSocket(tabs[0].webSocketDebuggerUrl);
let id=0;const cbs={};
const send=(m,params={})=>new Promise(r=>{const i=++id;cbs[i]=r;sock.send(JSON.stringify({id:i,method:m,params}));});
sock.on('message',d=>{const m=JSON.parse(d);if(m.id&&cbs[m.id])cbs[m.id](m);});
await new Promise((r,j)=>{sock.on('open',r);sock.on('error',j);});
await send('Page.enable');
await send('Runtime.enable');
await send('Page.navigate',{url:'http://localhost:4500/p/hawkeye-landscaping-inc'});
await wait(4000);
// scroll to services grid and capture that band
const ev=await send('Runtime.evaluate',{expression:`(()=>{const a=[...document.querySelectorAll('a[href*="/services/"]')].find(e=>e.querySelector('img')); const r=a?a.getBoundingClientRect():{top:1100}; return JSON.stringify({y:Math.max(0,r.top+window.scrollY-90)});})()`,returnByValue:true});
const {y}=JSON.parse(ev.result.result.value);
const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y,width:1440,height:1150,scale:1}});
fs.writeFileSync('/tmp/hawkeye_svc.png',Buffer.from(shot.result.data,'base64'));
console.log('SVC_DONE y='+y);
p.kill();
process.exit(0);
