import http from 'node:http';
import { spawn } from 'node:child_process';
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const port=9391;
const log=(...a)=>console.error('[shot]',...a);
const wait=ms=>new Promise(r=>setTimeout(r,ms));
log('launching chrome');
const p=spawn(CHROME,['--headless=new',`--remote-debugging-port=${port}`,'--hide-scrollbars','--window-size=1440,1000','about:blank'],{stdio:'ignore'});
await wait(2500);
const get=u=>new Promise((res,rej)=>http.get(u,r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>res(JSON.parse(d)));}).on('error',rej));
log('fetching tabs');
const tabs=await get(`http://127.0.0.1:${port}/json`);
log('tabs',tabs.length, tabs[0] && tabs[0].type);
const target=tabs.find(t=>t.type==='page')||tabs[0];
const WebSocket=(await import('ws')).default;
const sock=new WebSocket(target.webSocketDebuggerUrl);
let id=0;const cbs={};
const send=(m,params={})=>new Promise(r=>{const i=++id;cbs[i]=r;sock.send(JSON.stringify({id:i,method:m,params}));});
sock.on('message',d=>{const m=JSON.parse(d);if(m.id&&cbs[m.id]){const cb=cbs[m.id];delete cbs[m.id];cb(m);}});
await new Promise(r=>sock.on('open',r));
log('socket open');
await send('Page.enable');await send('Runtime.enable');
log('navigating');
await send('Page.navigate',{url:'http://localhost:4500/p/sonoran-landscape-design'});
await wait(4500);
log('capturing hero');
const fs=await import('node:fs');
let shot=await send('Page.captureScreenshot',{format:'png',clip:{x:0,y:0,width:1440,height:900,scale:1}});
fs.writeFileSync('/tmp/sonoran_hero.png',Buffer.from(shot.result.data,'base64'));
log('hero written');
const ev=await send('Runtime.evaluate',{expression:`(()=>{const a=[...document.querySelectorAll('a[href*="/services/"]')].find(e=>e.querySelector('img')); if(!a) return JSON.stringify({y:1100,h:1500}); const r=a.getBoundingClientRect(); return JSON.stringify({y:Math.max(0,r.top+window.scrollY+260), h:1500});})()`,returnByValue:true});
const {y,h}=JSON.parse(ev.result.result.value);
log('scrolling to services y',y);
await send('Runtime.evaluate',{expression:`window.scrollTo(0,${y})`});
await wait(1200);
shot=await send('Page.captureScreenshot',{format:'png',clip:{x:0,y:0,width:1440,height:Math.min(h,1500),scale:1}});
fs.writeFileSync('/tmp/sonoran_svc.png',Buffer.from(shot.result.data,'base64'));
log('svc written');
p.kill();process.exit(0);
