import http from 'node:http';
import { spawn } from 'node:child_process';
const log=(...a)=>console.error('[shot]',...a);
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const port=9353;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
log('spawning chrome');
const p=spawn(CHROME,['--headless=new',`--remote-debugging-port=${port}`,'--hide-scrollbars','--window-size=1440,1000','about:blank'],{stdio:'ignore'});
await wait(4500);
const get=u=>new Promise((res,rej)=>http.get(u,r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>res(JSON.parse(d)));}).on('error',rej));
log('fetching tabs');
const tabs=await get(`http://127.0.0.1:${port}/json`);
log('tabs',tabs.length);
const WebSocket=(await import('ws')).default;
const pg=tabs.find(t=>t.type==='page')||tabs[0];log('using',pg.url);const sock=new WebSocket(pg.webSocketDebuggerUrl);
let id=0;const cbs={};
const send=(m,params={})=>new Promise(r=>{const i=++id;cbs[i]=r;sock.send(JSON.stringify({id:i,method:m,params}));});
sock.on('message',d=>{const m=JSON.parse(d);if(m.id&&cbs[m.id])cbs[m.id](m);});
await new Promise((r,rej)=>{sock.on('open',r);sock.on('error',rej);});
log('ws open');
await send('Page.enable');
await send('Page.navigate',{url:'http://localhost:4500/p/ultimate-roofing-scottsdale'});
log('navigated, waiting render');
await wait(5000);
const fs=await import('node:fs');
let shot=await send('Page.captureScreenshot',{format:'png',clip:{x:0,y:0,width:1440,height:1000,scale:1.3}});
fs.writeFileSync('.tmp/057_hero.png',Buffer.from(shot.result.data,'base64'));
log('hero written');
const ev=await send('Runtime.evaluate',{expression:`(()=>{const a=[...document.querySelectorAll('a[href*="/services/"]')].find(e=>e.querySelector('img')); if(!a) return JSON.stringify({y:1100,h:1300}); const r=a.getBoundingClientRect(); return JSON.stringify({y:Math.max(0,r.top+window.scrollY-90), h:1250});})()`,returnByValue:true});
const {y,h}=JSON.parse(ev.result.result.value);
shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y,width:1440,height:h,scale:1.3}});
fs.writeFileSync('.tmp/057_svc.png',Buffer.from(shot.result.data,'base64'));
log('svc written y',y);
p.kill();process.exit(0);
