import http from 'node:http';
import { spawn } from 'node:child_process';
import fs from 'node:fs';
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const port=9351;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const p=spawn(CHROME,['--headless=new',`--remote-debugging-port=${port}`,'--hide-scrollbars','--window-size=1440,1000','about:blank'],{stdio:'ignore'});
await wait(2000);
const get=u=>new Promise((res,rej)=>http.get(u,r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>res(JSON.parse(d)));}).on('error',rej));
const tabs=await get(`http://127.0.0.1:${port}/json`);
const page=tabs.find(t=>t.type==='page')||tabs[0];
const WebSocket=(await import('ws')).default;
const sock=new WebSocket(page.webSocketDebuggerUrl);
let id=0;const cbs={};
const send=(m,params={})=>new Promise(r=>{const i=++id;cbs[i]=r;sock.send(JSON.stringify({id:i,method:m,params}));});
sock.on('message',d=>{const m=JSON.parse(d);if(m.id&&cbs[m.id])cbs[m.id](m);});
await new Promise(r=>sock.on('open',r));
await send('Page.enable');
await send('Runtime.enable');
await send('Page.navigate',{url:'http://localhost:4500/p/scottsdale-roofing-and-gutters'});
await wait(9000);
await send('Runtime.evaluate',{expression:'window.scrollTo(0,document.body.scrollHeight)'});
await wait(2000);
await send('Runtime.evaluate',{expression:'window.scrollTo(0,0)'});
await wait(1000);
fs.mkdirSync('_shots',{recursive:true});
const bands=[0,1000,3000,5000,7000];
for(let n=0;n<bands.length;n++){
  const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y:bands[n],width:1440,height:2000,scale:1}});
  if(shot?.result?.data) fs.writeFileSync(`_shots/scottsdale-${n}.png`,Buffer.from(shot.result.data,'base64'));
}
console.log('done');
p.kill();process.exit(0);
