import http from 'node:http';
import { spawn } from 'node:child_process';
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const port=9355;
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const p=spawn(CHROME,['--headless=new',`--remote-debugging-port=${port}`,'--hide-scrollbars','--window-size=1440,1000','about:blank'],{stdio:'ignore'});
await wait(2500);
const get=u=>new Promise((res,rej)=>http.get(u,r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>res(JSON.parse(d)));}).on('error',rej));
const tabs=await get(`http://127.0.0.1:${port}/json`);
const target=tabs.find(t=>t.type==='page')||tabs[0];
const WebSocket=(await import('ws')).default;
const sock=new WebSocket(target.webSocketDebuggerUrl);
let id=0;const cbs={};
const send=(m,params={})=>new Promise(r=>{const i=++id;cbs[i]=r;sock.send(JSON.stringify({id:i,method:m,params}));});
sock.on('message',d=>{const m=JSON.parse(d);if(m.id&&cbs[m.id])cbs[m.id](m);});
await new Promise(r=>sock.on('open',r));
await send('Page.enable');await send('Runtime.enable');
await send('Page.navigate',{url:'http://localhost:4500/p/united-roofing-and-general-contracting'});
await wait(5000);
await send('Runtime.evaluate',{expression:`window.scrollTo(0,document.body.scrollHeight)`});await wait(1200);
await send('Runtime.evaluate',{expression:`window.scrollTo(0,0)`});await wait(400);
const ev=await send('Runtime.evaluate',{expression:`String(document.body.scrollHeight)`,returnByValue:true});
const H=parseInt(ev.result.result.value,10);
const fs=await import('node:fs');
let n=0;
for(let y=2700;y<H;y+=1300){
  const shot=await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true,clip:{x:0,y,width:1440,height:Math.min(1300,H-y),scale:1}});
  fs.writeFileSync(`.tmp/ucg_low${++n}.png`,Buffer.from(shot.result.data,'base64'));
}
console.log('H',H,'slices',n);
p.kill();process.exit(0);
